import assert from 'node:assert/strict';
import { AdaptiveInk,pointerSamples } from '../js/ink.js';
const e={getCoalescedEvents:()=>[]};assert.deepEqual(pointerSamples(e),[e]);
let f=new AdaptiveInk([0,0],0,0);assert.deepEqual(f.add([3,7],8),[3,7]);
f=new AdaptiveInk([0,0],0,.85);let jitter=0;for(let i=1;i<100;i++)jitter+=Math.abs(f.add([0,i%2?.5:-.5],i*8)[1]);assert(jitter<25,'Slow tremor should be attenuated');
f=new AdaptiveInk([0,0],0,.85);let p;for(let i=1;i<20;i++)p=f.add([i*10,0],i*8);assert(190-p[0]<3,'Fast strokes should track within 3px');
console.log('Adaptive sampling checks passed');
const {refineInk,naturalPathD}=await import('../js/ink.js');
const raw=Array.from({length:101},(_,i)=>[i,i===0||i===100?0:(i%2?.6:-.6)]),smoothed=refineInk(raw,.85);
assert.deepEqual(smoothed[0],raw[0]);assert.deepEqual(smoothed.at(-1),raw.at(-1));assert(smoothed.reduce((a,p)=>a+Math.abs(p[1]),0)/smoothed.length<.4);
assert.deepEqual(refineInk(raw,0),raw);assert.deepEqual(refineInk([[2,3]],.85),[[2,3]]);
const corner=refineInk([[0,0],[10,0],[10,10]],.85);assert(corner.some(p=>Math.hypot(p[0]-10,p[1])<.1),'Right-angle corner preserved');
assert(!/NaN|Infinity/.test(naturalPathD(smoothed)));assert(naturalPathD(smoothed).includes(' C'));
console.log('Finished stroke endpoint, corner, jitter and curve checks passed');
