import { createBoard, parseBackup } from './model.js?v=20260923-2';
import { BoardRepository } from './storage.js?v=20260923-2';
import { Editor } from './editor.js?v=20260923-2';
import { el, btn, formDialog, confirmDialog, chooseFile, notify } from './ui.js?v=20260923-2';
import { backup } from './export.js?v=20260923-2';
import { drawItem, svgEl, union } from './scene.js?v=20260923-2';

const repository=new BoardRepository(),app=document.querySelector('#app');
let editor=null,generation=0,viewTrash=false,folderFilter='',searchText='',sortBy='recent';
async function settings(board){const r=await formDialog(board?'Lesson settings':'New lesson',[['title','Lesson title',board?.title||'Untitled lesson'],['folder','Folder (optional)',board?.folder||'']],{validate:v=>{if(!v.title.trim()||v.title.length>200||v.folder.length>200)throw new Error('Use a title and folder under 200 characters.');return {...v,title:v.title.trim(),folder:v.folder.trim()};}});if(!r)return;const saved=await repository.save({...board||createBoard(),...r});if(board)await renderRoute();else location.hash=`/board/${saved.id}`;}
function thumbnail(board){const svg=svgEl('svg',{'aria-hidden':'true',class:'thumbnail'}),b=union(board.items);svg.setAttribute('viewBox',`${b.x-20} ${b.y-20} ${b.w+40} ${b.h+40}`);board.items.forEach(i=>svg.append(drawItem(i)));return svg;}
async function importBackup(){const [file]=await chooseFile('.json,application/json');if(!file)return;if(file.size>25_000_000)throw new Error('Backup exceeds the 25 MB limit.');const board=parseBackup(await file.text());board.id=crypto.randomUUID();board.revision=0;board.deleted=false;board.title=board.title.slice(0,188)+' (imported)';await repository.save(board);location.hash=`/board/${board.id}`;}
async function dashboard(token){const boards=await repository.list();if(token!==generation)return;app.className='dashboard';app.replaceChildren();
 const heading=el('div',null,'heading'),intro=el('div');intro.append(el('p','PERSONAL TEACHING WORKSPACE','eyebrow'),el('h1',viewTrash?'Recently deleted':'Your lessons, all in one place'),el('p','Draw an idea. Explore a function. Make the explanation clear.','muted'));
 const actions=el('div',null,'actions');actions.append(btn('Import backup',importBackup),btn('+ New lesson',()=>settings(null),'primary'));heading.append(intro,actions);
 const controls=el('div',null,'dashboard-controls'),search=el('input',null,'search');search.type='search';search.placeholder='Search lessons…';search.setAttribute('aria-label','Search lessons');search.value=searchText;
 const folders=el('select');folders.setAttribute('aria-label','Filter by folder');for(const name of ['',...new Set(boards.filter(b=>!b.deleted).map(b=>b.folder).filter(Boolean))].sort()){const o=el('option',name||'All folders');o.value=name;folders.append(o);}folders.value=folderFilter;
 const sort=el('select');sort.setAttribute('aria-label','Sort lessons');for(const [value,label] of [['recent','Recently edited'],['title','Title A–Z'],['oldest','Oldest first']]){const o=el('option',label);o.value=value;sort.append(o);}sort.value=sortBy;
 const trash=btn(viewTrash?'← All lessons':`Trash (${boards.filter(b=>b.deleted).length})`,async()=>{viewTrash=!viewTrash;await renderRoute();});controls.append(search,folders,sort,trash);
 const cards=el('div',null,'cards');function draw(){cards.replaceChildren();let list=boards.filter(b=>b.deleted===viewTrash&&(!folderFilter||viewTrash||b.folder===folderFilter)&&`${b.title} ${b.folder}`.toLowerCase().includes(searchText.toLowerCase()));list.sort((a,b)=>sortBy==='title'?a.title.localeCompare(b.title):sortBy==='oldest'?a.updatedAt.localeCompare(b.updatedAt):b.updatedAt.localeCompare(a.updatedAt));if(!list.length){const empty=el('div',null,'empty');empty.append(el('h2',viewTrash?'Your trash is empty':'Make room for your next idea'),el('p',searchText?'No matching lessons.':'Create a lesson or import a backup to get started.','muted'));cards.append(empty);}for(const board of list){const card=el('article',null,'card'),body=el('div',null,'card-body'),title=el('h2',board.title);title.dir='auto';const actions=el('div',null,'actions');
 if(viewTrash)actions.append(btn('Restore',async()=>{await repository.save({...board,deleted:false});await renderRoute();},'primary'));
 else actions.append(btn('Open',()=>location.hash=`/board/${board.id}`,'primary'),btn('Settings',()=>settings(board)),btn('Duplicate',async()=>{await repository.save({...structuredClone(board),id:crypto.randomUUID(),title:board.title.slice(0,188)+' (copy)',revision:0,createdAt:new Date().toISOString()});await renderRoute();}),btn('Move to trash',async()=>{if(await confirmDialog('Move lesson to trash?',board.title+' can be restored from Trash.')){await repository.save({...board,deleted:true});await renderRoute();}}));
 actions.append(btn('Backup',()=>backup(board)));body.append(el('span',board.folder||'Unfiled','folder-tag'),title,el('small',`${new Date(board.updatedAt).toLocaleDateString()} · ${board.items.length} objects`),actions);card.append(thumbnail(board),body);cards.append(card);}}
 search.oninput=()=>{searchText=search.value;draw();};folders.onchange=()=>{folderFilter=folders.value;draw();};sort.onchange=()=>{sortBy=sort.value;draw();};draw();
 const footer=el('p','Saved on this device. Use editable backups to move lessons between computers or protect them before clearing browser data.','storage-note');app.append(heading,controls,cards,footer);}
async function renderRoute(){const token=++generation;try{if(editor){await editor.flush();if(token!==generation)return;editor.dispose();editor=null;}app.setAttribute('aria-busy','true');const match=location.hash.match(/^#\/board\/([a-zA-Z0-9-]+)$/);if(match){const board=await repository.get(match[1]);if(token!==generation)return;if(!board||board.deleted)throw new Error('Lesson not found. Return to Lessons using the logo.');editor=new Editor(app,board,repository);}else await dashboard(token);}catch(error){notify(error.message);if(!editor)app.replaceChildren(el('p',error.message));}finally{app.setAttribute('aria-busy','false');}}
window.addEventListener('hashchange',renderRoute);window.addEventListener('beforeunload',e=>{if(editor?.queue.dirty || editor?.drag){e.preventDefault();e.returnValue='';}});
renderRoute();
