import { el, btn, formDialog, chooseFile, notify, confirmDialog } from './ui.js?v=20260923-2';
import { svgEl, drawItem, background, bounds, union } from './scene.js?v=20260924-1';
import { toWorld, zoomAt } from './viewport.js?v=20260923-2';
import { History } from './history.js?v=20260923-2';
import { SaveQueue } from './save-queue.js?v=20260923-2';
import { equation, graph, importImage, importPDF } from './media.js?v=20260923-2';
import { exportBoard, backup } from './export.js?v=20260924-1';
import { validateBoard } from './model.js?v=20260923-2';
import { smoothInk } from './ink.js?v=20260924-1';

const TOOLS=[['select','↖','Select (V)'],['pan','✋','Pan (H)'],['pen','✎','Pen (P)'],['highlighter','▰','Highlighter'],['eraser','⌫','Object eraser (E)'],['line','╱','Line (L)'],['arrow','↗','Arrow'],['rectangle','□','Rectangle (R)'],['ellipse','○','Ellipse (O)'],['triangle','△','Triangle'],['polygon','⬠','Polygon: click vertices, Enter to finish'],['text','T','Text (T)'],['note','▤','Sticky note'],['equation','ƒ','Equation'],['graph','⌁','Function graph'],['image','▧','Image'],['pdf','▥','PDF pages'],['laser','●','Laser pointer']];
export class Editor {
 constructor(root,board,repository){this.root=root;this.board=board;this.repo=repository;this.selected=new Set();this.tool='select';this.stroke='#243c59';this.fill='none';this.lineWidth=3;this.opacity=1;this.fontSize=26;this.inkSmoothing=.65;this.history=new History(this.document());this.clipboard=[];this.polygon=[];this.disposed=false;this.queue=new SaveQueue(async snapshot=>{const saved=await this.repo.save({...snapshot,revision:this.board.revision});this.board.revision=saved.revision;this.board.updatedAt=saved.updatedAt;},(state,error)=>{this.saveState.textContent=state==='saving'?'Saving…':state==='saved'?'Saved on this device':'Save failed — back up your work';this.saveState.classList.toggle('error',state==='error');this.retry.hidden=state!=='error';if(error)notify(error.message);});this.build();this.keyHandler=e=>this.onKey(e);window.addEventListener('keydown',this.keyHandler);this.keyUp=e=>{if(e.code==='Space'){this.space=false;this.svg.style.cursor=this.tool==='pan'?'grab':'crosshair';}};window.addEventListener('keyup',this.keyUp);this.blur=()=>{this.space=false;};window.addEventListener('blur',this.blur);}
 document(){return structuredClone({items:this.board.items,background:this.board.background});}
 async flush(){await this.queue.flush();}
 dispose(){this.disposed=true;window.removeEventListener('keydown',this.keyHandler);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.blur);clearInterval(this.clock);document.body.classList.remove('presenting');}
 save(){this.queue.enqueue(this.board).catch(()=>{});}
 commit(){try{validateBoard(this.board);this.history.commit(this.document());this.save();this.paint();}catch(e){Object.assign(this.board,structuredClone(this.history.current));this.paint();throw e;}}
 async action(fn){try{await fn();}catch(e){notify(e.message);}}
 build(){this.root.className='editor';this.root.replaceChildren();const top=el('div',null,'editor-top');top.setAttribute('role','toolbar');top.setAttribute('aria-label','Teaching board toolbar');const back=el('a','← Lessons','button');back.href='#/';this.title=btn(this.board.title,async()=>{const r=await formDialog('Lesson settings',[['title','Title',this.board.title],['folder','Folder',this.board.folder]],{validate:v=>{if(!v.title.trim()||v.title.length>200||v.folder.length>200)throw new Error('Use a title and folder under 200 characters.');return v;}});if(r){Object.assign(this.board,r);this.title.textContent=r.title;this.save();}},'lesson-title');this.title.dir='auto';
 this.saveState=el('span','Saved on this device','save-state');this.retry=btn('Retry save',()=>this.flush());this.retry.hidden=true;
 const exports=el('select');exports.setAttribute('aria-label','Export lesson');for(const [v,t] of [['','Export…'],['json','Editable backup'],['svg','SVG image'],['png','PNG image'],['pdf','Print / Save as PDF']]){const o=el('option',t);o.value=v;exports.append(o);}exports.onchange=()=>{const format=exports.value;exports.value='';if(format)this.action(()=>exportBoard(this.board,format));};
 top.append(back,this.title,this.saveState,this.retry,exports,btn('Present',()=>{document.body.classList.toggle('presenting');}),btn('Help',()=>this.help()));
 const bar=el('div',null,'tools');this.toolButtons=new Map();for(const [id,icon,label] of TOOLS){const b=btn(icon,()=>this.setTool(id),'tool');b.title=label;b.setAttribute('aria-label',label);this.toolButtons.set(id,b);bar.append(b);}this.undoButton=btn('↶',()=>this.undo());this.undoButton.title='Undo (Ctrl+Z)';this.undoButton.setAttribute('aria-label','Undo');this.redoButton=btn('↷',()=>this.redo());this.redoButton.title='Redo (Ctrl+Shift+Z)';this.redoButton.setAttribute('aria-label','Redo');bar.append(this.undoButton,this.redoButton);
 const properties=el('div',null,'properties');const color=el('input');color.type='color';color.value=this.stroke;color.setAttribute('aria-label','Stroke color');color.onchange=()=>{this.stroke=color.value;this.modify({stroke:color.value});};
 const fill=el('input');fill.type='color';fill.value='#fff1a8';fill.setAttribute('aria-label','Fill color');fill.onchange=()=>{this.fill=fill.value;this.modify({fill:fill.value});};
 const width=el('select');width.setAttribute('aria-label','Line width');for(const n of [1,2,3,5,8,12,20]){const o=el('option',n+' px');o.value=n;width.append(o);}width.value=3;width.onchange=()=>{this.lineWidth=+width.value;this.modify({lineWidth:+width.value});};
 const opacity=el('input');opacity.type='range';opacity.min=.1;opacity.max=1;opacity.step=.1;opacity.value=1;opacity.title='Opacity';opacity.setAttribute('aria-label','Opacity');opacity.onchange=()=>{this.opacity=+opacity.value;this.modify({opacity:+opacity.value});};
 const font=el('select');font.setAttribute('aria-label','Text size');for(const n of [16,20,26,32,40,56,72]){const o=el('option',n+' pt');o.value=n;font.append(o);}font.value=26;font.onchange=()=>{this.fontSize=+font.value;this.modify({fontSize:+font.value});};
 const paper=el('select');paper.setAttribute('aria-label','Board background');for(const type of ['grid','dots','ruled','plain','dark']){const o=el('option',type[0].toUpperCase()+type.slice(1));o.value=type;paper.append(o);}paper.value=this.board.background;paper.onchange=()=>{this.board.background=paper.value;this.commit();};this.paper=paper;
 const smoothing=el('select');smoothing.setAttribute('aria-label','Ink smoothing');for(const [value,label] of [[0,'Ink: Off'],[.35,'Ink: Low'],[.65,'Ink: Medium'],[.85,'Ink: High']]){const o=el('option',label);o.value=value;smoothing.append(o);}smoothing.value=this.inkSmoothing;smoothing.onchange=()=>{this.inkSmoothing=+smoothing.value;let changed=false;for(const item of this.board.items)if(this.selected.has(item.id)&&item.type==='path'&&!item.locked){if(item.rawPoints)item.points=smoothInk(item.rawPoints,this.inkSmoothing);item.smoothing=this.inkSmoothing;changed=true;}if(changed)this.commit();};this.smoothingSelect=smoothing;
 properties.append(el('span','Stroke'),color,el('span','Fill'),fill,btn('No fill',()=>{this.fill='none';this.modify({fill:'none'});}),width,font,el('span','Opacity'),opacity,el('span','Ink'),smoothing,paper);top.append(bar,properties);
 const layout=el('div',null,'editor-layout');this.area=el('div',null,'board');this.svg=svgEl('svg',{'aria-label':'Teaching canvas',tabindex:0});this.area.append(this.svg);
 this.zoomLabel=el('span');const zoom=el('div',null,'zoom');zoom.append(btn('−',()=>this.zoom(1/1.2)),this.zoomLabel,btn('+',()=>this.zoom(1.2)),btn('Fit',()=>this.fit()),btn('100%',()=>{this.board.viewport={x:0,y:0,zoom:1};this.paint();this.save();}));this.area.append(zoom);
 this.exitPresent=btn('Exit presentation',()=>document.body.classList.remove('presenting'),'exit-present');this.area.append(this.exitPresent);
 const side=el('aside',null,'inspector');side.append(el('h2','Selection'));this.selectionLabel=el('p','No objects selected','muted');side.append(this.selectionLabel);const actions=el('div',null,'selection-actions');actions.append(btn('Edit content',()=>this.editSelected()),btn('Duplicate',()=>this.duplicate()),btn('Delete',()=>this.remove()),btn('Bring to front',()=>this.layer(true)),btn('Send to back',()=>this.layer(false)),btn('Lock / Unlock',()=>{for(const i of this.board.items)if(this.selected.has(i.id))i.locked=!i.locked;this.commit();}),btn('Rotate',async()=>{const r=await formDialog('Rotate selection',[['angle','Angle in degrees',0,'number']],{validate:v=>{const n=+v.angle;if(!Number.isFinite(n))throw new Error('Enter a number.');return n;}});if(r!==null)this.modify({rotation:r});}),btn('Size',()=>this.resizeDialog()));side.append(actions,el('h2','Lesson timer'));this.timerLabel=el('strong','00:00','timer');side.append(this.timerLabel,btn('Set timer',()=>this.timer()),btn('Pause / Resume',()=>{this.paused=!this.paused;}),el('p','Double-click text, equations, or graphs to edit. Shift-click selects several objects.','muted'));layout.append(this.area,side);this.root.append(top,layout);this.toolHint=el('div',null,'tool-hint');this.root.append(this.toolHint);
 this.svg.onpointerdown=e=>this.pointerDown(e);this.svg.onpointermove=e=>this.pointerMove(e);this.svg.onpointerup=e=>this.pointerUp(e);this.svg.onpointercancel=e=>{this.drag=null;this.draft=null;Object.assign(this.board,structuredClone(this.history.current));this.paint();};this.svg.ondblclick=e=>{const id=e.target.closest('[data-id]')?.getAttribute('data-id');if(id){this.selected=new Set([id]);this.action(()=>this.editSelected());}};
 this.svg.onwheel=e=>{e.preventDefault();if(e.ctrlKey||e.metaKey){this.board.viewport=zoomAt(this.board.viewport,this.screen(e),Math.exp(-e.deltaY*.002));}else{this.board.viewport.x-=e.deltaX;this.board.viewport.y-=e.deltaY;}this.paint();this.save();};this.setTool('select');this.paint();}
 setTool(tool){if(['image','pdf'].includes(tool)){this.action(()=>this.insertMedia(tool));return;}if(['equation','graph'].includes(tool)){this.action(()=>this.insertMath(tool));return;}this.tool=tool;this.polygon=[];this.draft=null;for(const [id,b]of this.toolButtons)b.setAttribute('aria-pressed',String(id===tool));this.svg.style.cursor=tool==='pan'?'grab':tool==='select'?'default':'crosshair';this.toolHint.textContent=tool==='polygon'?'Click vertices · Enter to finish · Escape to cancel':tool==='select'?'Select and drag objects · Drag the corner to resize · Space + drag to pan':`${TOOLS.find(t=>t[0]===tool)?.[2]||tool} · Space + drag to pan`;this.paint();}
 screen(e){const r=this.svg.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
 point(e){return toWorld(this.screen(e),this.board.viewport);}
 center(){return toWorld({x:this.area.clientWidth/2,y:this.area.clientHeight/2},this.board.viewport);}
 base(type,p){return {id:crypto.randomUUID(),type,x:p.x,y:p.y,w:1,h:1,stroke:this.stroke,fill:this.fill,lineWidth:this.lineWidth,opacity:this.opacity,rotation:0,locked:false};}
 paint(){this.svg.replaceChildren();background(this.svg,this.board.background,this.board.viewport);const v=this.board.viewport,scene=svgEl('g',{transform:`translate(${v.x} ${v.y}) scale(${v.zoom})`});this.board.items.forEach(i=>scene.append(drawItem(i)));if(this.draft)scene.append(drawItem(this.draft));
 for(const i of this.board.items){if(this.selected.has(i.id)){const b=bounds(i);scene.append(svgEl('rect',{x:b.x-3,y:b.y-3,width:b.w+6,height:b.h+6,fill:'none',stroke:i.locked?'#d59a30':'#168fa5','stroke-width':1.5/v.zoom,'stroke-dasharray':`${5/v.zoom} ${3/v.zoom}`,'pointer-events':'none'}));}}
 const selected=this.board.items.filter(i=>this.selected.has(i.id)&&!i.locked);if(selected.length&&this.tool==='select'){const b=union(selected);scene.append(svgEl('rect',{x:b.x+b.w-5/v.zoom,y:b.y+b.h-5/v.zoom,width:10/v.zoom,height:10/v.zoom,fill:'#147d92',stroke:'#fff','stroke-width':1/v.zoom,'data-resize':'true',cursor:'nwse-resize'}));}
 if(this.marquee)scene.append(svgEl('rect',{...this.marquee,fill:'#147d9215',stroke:'#147d92','stroke-width':1/v.zoom,'pointer-events':'none'}));
 this.svg.append(scene);this.zoomLabel.textContent=Math.round(v.zoom*100)+'%';this.selectionLabel.textContent=this.selected.size?`${this.selected.size} selected · ${this.board.items.length} objects`:`${this.board.items.length} objects`;this.undoButton.disabled=!this.history.past.length;this.redoButton.disabled=!this.history.future.length;this.paper.value=this.board.background;const path=this.board.items.find(i=>this.selected.has(i.id)&&i.type==='path');this.smoothingSelect.value=String(path?.smoothing??this.inkSmoothing);}
 pointerDown(e){if(e.button!==0&&e.button!==1)return;if(this.drag)return;e.preventDefault();this.svg.focus();const p=this.point(e),screen=this.screen(e);this.svg.setPointerCapture(e.pointerId);
 if(this.space||this.tool==='pan'||e.button===1){this.drag={kind:'pan',screen,v:{...this.board.viewport}};return;}
 if(this.tool==='laser'){this.drag={kind:'laser'};this.laser(p);return;}
 const id=e.target.closest('[data-id]')?.getAttribute('data-id'),item=this.board.items.find(i=>i.id===id);
 if(this.tool==='eraser'){this.drag={kind:'erase'};this.eraseAt(p);return;}
 if(this.tool==='select'){
 if(e.target.hasAttribute('data-resize')){const items=this.board.items.filter(i=>this.selected.has(i.id)&&!i.locked);this.drag={kind:'resize',start:p,b:union(items),items:structuredClone(items)};return;}
 if(item){if(e.shiftKey){if(this.selected.has(id))this.selected.delete(id);else this.selected.add(id);}else if(!this.selected.has(id))this.selected=new Set([id]);this.drag={kind:'move',start:p,items:structuredClone(this.board.items.filter(i=>this.selected.has(i.id)&&!i.locked))};}
 else{if(!e.shiftKey)this.selected.clear();this.drag={kind:'marquee',start:p};}this.paint();return;}
 if(['text','note'].includes(this.tool)){this.action(()=>this.insertText(this.tool,p));return;}
 if(this.tool==='polygon'){this.polygon.push([p.x,p.y]);this.updatePolygon();return;}
 const type=['pen','highlighter'].includes(this.tool)?'path':this.tool;this.draft=this.base(type,p);if(this.tool==='highlighter'){this.draft.opacity=.3;this.draft.lineWidth=Math.max(14,this.lineWidth*4);}if(type==='path'){this.draft.smoothing=this.inkSmoothing;this.draft.points=[[0,0]];this.draft.rawPoints=[[0,0]];}else this.draft.points=[[0,0],[.1,.1]];this.drag={kind:'draw',start:p,lastRaw:[0,0],lastSmooth:[0,0]};this.paint();}
 pointerMove(e){const p=this.point(e);if(!this.drag)return;const d=this.drag;
 if(d.kind==='pan'){const s=this.screen(e);this.board.viewport={...d.v,x:d.v.x+s.x-d.screen.x,y:d.v.y+s.y-d.screen.y};}
 if(d.kind==='laser'){this.laser(p);return;}
 if(d.kind==='erase'){this.eraseAt(p);return;}
 if(d.kind==='move'){for(const old of d.items){const item=this.board.items.find(i=>i.id===old.id);item.x=old.x+p.x-d.start.x;item.y=old.y+p.y-d.start.y;}}
 if(d.kind==='resize'){const sx=Math.max(.05,(p.x-d.b.x)/Math.max(1,d.b.w)),sy=Math.max(.05,(p.y-d.b.y)/Math.max(1,d.b.h));for(const old of d.items){const i=this.board.items.find(i=>i.id===old.id);i.x=d.b.x+(old.x-d.b.x)*sx;i.y=d.b.y+(old.y-d.b.y)*sy;i.w=Math.max(1,old.w*sx);i.h=Math.max(1,old.h*sy);if(old.points)i.points=old.points.map(([x,y])=>[x*sx,y*sy]);if(old.rawPoints)i.rawPoints=old.rawPoints.map(([x,y])=>[x*sx,y*sy]);if(['text','note'].includes(i.type))i.fontSize=(old.fontSize||26)*Math.min(sx,sy);}}
 if(d.kind==='marquee')this.marquee={x:Math.min(p.x,d.start.x),y:Math.min(p.y,d.start.y),width:Math.abs(p.x-d.start.x),height:Math.abs(p.y-d.start.y)};
 if(d.kind==='draw'){const i=this.draft;if(i.type==='path'){const events=e.getCoalescedEvents?.()||[e];for(const sample of events){const point=this.point(sample),pt=[point.x-d.start.x,point.y-d.start.y];if(Math.hypot(pt[0]-d.lastRaw[0],pt[1]-d.lastRaw[1])<=1/this.board.viewport.zoom)continue;i.rawPoints.push(pt);d.lastRaw=pt;const amount=i.smoothing||0;const alpha=amount?Math.max(.14,1-amount*.78):1;const previous=d.lastSmooth||pt;const smooth=[previous[0]+(pt[0]-previous[0])*alpha,previous[1]+(pt[1]-previous[1])*alpha];if(Math.hypot(smooth[0]-previous[0],smooth[1]-previous[1])>1/this.board.viewport.zoom||i.points.length===1)i.points.push(smooth);d.lastSmooth=smooth;}}else{i.x=Math.min(p.x,d.start.x);i.y=Math.min(p.y,d.start.y);i.w=Math.max(1,Math.abs(p.x-d.start.x));i.h=Math.max(1,Math.abs(p.y-d.start.y));if(e.shiftKey&&!['line','arrow'].includes(i.type))i.w=i.h=Math.max(i.w,i.h);i.points=[[d.start.x-i.x,d.start.y-i.y],[p.x-i.x,p.y-i.y]];}}
 this.paint();}
 pointerUp(e){if(!this.drag)return;const d=this.drag;this.drag=null;if(d.kind==='draw'){const i=this.draft;if(i.type==='path'){if(e&&i.rawPoints?.length){const point=this.point(e),pt=[point.x-d.start.x,point.y-d.start.y];if(Math.hypot(pt[0]-d.lastRaw[0],pt[1]-d.lastRaw[1])>1/this.board.viewport.zoom)i.rawPoints.push(pt);}i.points=smoothInk(i.rawPoints||i.points,i.smoothing||0);const xs=i.points.map(p=>p[0]),ys=i.points.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys);i.x+=x;i.y+=y;i.w=Math.max(1,Math.max(...xs)-x);i.h=Math.max(1,Math.max(...ys)-y);i.points=i.points.map(p=>[p[0]-x,p[1]-y]);if(i.rawPoints)i.rawPoints=i.rawPoints.map(p=>[p[0]-x,p[1]-y]);}this.board.items.push(i);this.draft=null;this.selected.clear();}
 if(d.kind==='marquee'&&this.marquee){const m=this.marquee;for(const i of this.board.items){const b=bounds(i);if(b.x>=m.x&&b.y>=m.y&&b.x+b.w<=m.x+m.width&&b.y+b.h<=m.y+m.height)this.selected.add(i.id);}this.marquee=null;}
 if(['draw','move','resize','erase'].includes(d.kind))this.action(()=>this.commit());else if(d.kind==='pan')this.save();this.paint();}
 eraseAt(p){const i=[...this.board.items].reverse().find(i=>{const b=bounds(i);return !i.locked&&p.x>=b.x-4&&p.x<=b.x+b.w+4&&p.y>=b.y-4&&p.y<=b.y+b.h+4;});if(i){this.board.items=this.board.items.filter(v=>v!==i);this.selected.delete(i.id);this.paint();}}
 laser(p){this.svg.querySelector('.laser')?.remove();const s=svgEl('circle',{cx:p.x*this.board.viewport.zoom+this.board.viewport.x,cy:p.y*this.board.viewport.zoom+this.board.viewport.y,r:7,fill:'#f34c5e','pointer-events':'none',class:'laser'});this.svg.append(s);clearTimeout(this.laserTimer);this.laserTimer=setTimeout(()=>s.remove(),500);}
 updatePolygon(){if(!this.polygon.length)return;const x=Math.min(...this.polygon.map(p=>p[0])),y=Math.min(...this.polygon.map(p=>p[1]));this.draft={...this.base('polygon',{x,y}),points:this.polygon.map(p=>[p[0]-x,p[1]-y]),w:Math.max(1,Math.max(...this.polygon.map(p=>p[0]))-x),h:Math.max(1,Math.max(...this.polygon.map(p=>p[1]))-y)};this.paint();}
 finishPolygon(){if(this.polygon.length<3){notify('Choose at least three vertices.');return;}this.board.items.push(this.draft);this.draft=null;this.polygon=[];this.commit();}
 modify(props){let changed=false;for(const item of this.board.items)if(this.selected.has(item.id)&&!item.locked){Object.assign(item,props);changed=true;}if(changed)this.commit();}
 remove(){this.board.items=this.board.items.filter(i=>!this.selected.has(i.id)||i.locked);this.selected.clear();this.commit();}
 duplicate(){const items=this.board.items.filter(i=>this.selected.has(i.id));this.paste(items);}
 paste(items=this.clipboard){const copies=structuredClone(items).map(i=>({...i,id:crypto.randomUUID(),x:i.x+30,y:i.y+30,locked:false}));this.board.items.push(...copies);this.selected=new Set(copies.map(i=>i.id));this.commit();}
 layer(front){const chosen=this.board.items.filter(i=>this.selected.has(i.id)&&!i.locked),rest=this.board.items.filter(i=>!chosen.includes(i));this.board.items=front?[...rest,...chosen]:[...chosen,...rest];this.commit();}
 undo(){const doc=this.history.undo();if(doc){Object.assign(this.board,doc);this.selected.clear();this.save();this.paint();}}
 redo(){const doc=this.history.redo();if(doc){Object.assign(this.board,doc);this.selected.clear();this.save();this.paint();}}
 zoom(factor){this.board.viewport=zoomAt(this.board.viewport,{x:this.area.clientWidth/2,y:this.area.clientHeight/2},factor);this.paint();this.save();}
 fit(){if(!this.board.items.length)return;const b=union(this.board.items),z=Math.max(.1,Math.min(3,(this.area.clientWidth-80)/Math.max(1,b.w),(this.area.clientHeight-80)/Math.max(1,b.h)));this.board.viewport={zoom:z,x:(this.area.clientWidth-b.w*z)/2-b.x*z,y:(this.area.clientHeight-b.h*z)/2-b.y*z};this.paint();this.save();}
 async resizeDialog(){const i=this.board.items.find(i=>this.selected.has(i.id));if(!i){notify('Select an object first.');return;}const r=await formDialog('Object size',[['w','Width',i.w,'number'],['h','Height',i.h,'number']],{validate:v=>{const w=+v.w,h=+v.h;if(!Number.isFinite(w)||!Number.isFinite(h)||w<1||h<1||w>10000||h>10000)throw new Error('Use sizes from 1 to 10,000.');return {w,h};}});if(r){for(const item of this.board.items.filter(i=>this.selected.has(i.id)&&!i.locked)){if(item.points)item.points=item.points.map(([x,y])=>[x*r.w/item.w,y*r.h/item.h]);if(item.rawPoints)item.rawPoints=item.rawPoints.map(([x,y])=>[x*r.w/item.w,y*r.h/item.h]);Object.assign(item,r);}this.commit();}}
 async insertText(type,p=this.center(),existing=null){const r=await formDialog(type==='note'?'Sticky note':'Text',[['text','Text (Hebrew supported)',existing?.text||'','textarea']],{validate:v=>{if(!v.text.trim()||v.text.length>10000)throw new Error('Enter text up to 10,000 characters.');return v;}});if(!r||this.disposed)return;const item=existing||{...this.base(type,p),w:type==='note'?260:360,h:130,fontSize:this.fontSize,fill:type==='note'?'#fff1a8':'none'};item.text=r.text;item.h=Math.max(item.h,(r.text.split('\n').length+Math.ceil(r.text.length/25))*item.fontSize*1.3+20);if(!existing)this.board.items.push(item);this.selected=new Set([item.id]);this.setTool('select');this.commit();}
 async insertMath(type,existing=null){const fields=type==='equation'?[['source','LaTeX',existing?.source||'y=\\frac{1}{2}x^2']]:[['source','f(x) =',existing?.source||'x^2'],['xmin','x minimum',existing?.range?.[0]??-5,'number'],['xmax','x maximum',existing?.range?.[2]??5,'number'],['ymin','y minimum',existing?.range?.[3]??-5,'number'],['ymax','y maximum',existing?.range?.[1]??5,'number']];
 const value=await formDialog(type==='equation'?'Insert equation':'Function graph',fields,{note:type==='graph'?'Use x, + − * / ^, sin, cos, tan, sqrt, abs, pi. Angles are radians. Example: sin(x) or 2*x^2-3.':'Examples: \\frac{a}{b}, \\sqrt{x}, \\int_0^1 x^2\\,dx',submit:'Render and insert',validate:async v=>type==='equation'?equation(v.source):graph(v.source,[+v.xmin,+v.ymax,+v.xmax,+v.ymin])});if(!value||this.disposed)return;const item=existing||this.base(type,this.center());const old=existing?{w:existing.w,h:existing.h}:{};Object.assign(item,value,old);if(!existing)this.board.items.push(item);this.selected=new Set([item.id]);this.setTool('select');this.commit();}
 async editSelected(){const selected=this.board.items.filter(i=>this.selected.has(i.id));if(selected.length!==1){notify('Select one object to edit.');return;}const i=selected[0];if(i.locked){notify('Unlock this object first.');return;}if(['text','note'].includes(i.type))await this.insertText(i.type,{x:i.x,y:i.y},i);else if(['equation','graph'].includes(i.type))await this.insertMath(i.type,i);else notify('Use the color, size, rotation, and layer controls to edit this object.');}
 async insertMedia(type){const files=await chooseFile(type==='pdf'?'.pdf,application/pdf':'image/png,image/jpeg,image/webp,image/gif',type==='image');if(!files.length||this.disposed)return;notify('Preparing media…');const items=[];let p=this.center();for(const file of files){const images=type==='pdf'?await importPDF(file,notify):[await importImage(file)];for(const data of images){items.push({...this.base('image',p),...data,locked:type==='pdf'});p={x:p.x,y:p.y+data.h+35};}}if(this.disposed)return;validateBoard({...this.board,items:[...this.board.items,...items]});this.board.items.push(...items);this.selected=new Set(items.map(i=>i.id));this.setTool('select');this.commit();this.fit();notify(type==='pdf'?'PDF pages imported and locked. Draw on top, or unlock to move.':'Images inserted.');}
 async timer(){const r=await formDialog('Lesson timer',[['minutes','Minutes',5,'number']],{validate:v=>{const n=+v.minutes;if(!Number.isFinite(n)||n<=0||n>180)throw new Error('Choose 1–180 minutes.');return n;}});if(!r)return;clearInterval(this.clock);this.remaining=Math.round(r*60);this.paused=false;const draw=()=>{this.timerLabel.textContent=String(Math.floor(this.remaining/60)).padStart(2,'0')+':'+String(this.remaining%60).padStart(2,'0');};draw();this.clock=setInterval(()=>{if(this.paused)return;this.remaining--;draw();if(this.remaining<=0){clearInterval(this.clock);notify('Lesson timer finished.');}},1000);}
 async help(){await formDialog('Whiteboard shortcuts',[],{note:'V select · H pan · P pen · E erase · L line · R rectangle · O ellipse · T text. Use the Ink selector for handwriting smoothing. Space + drag pans. Ctrl/⌘ + wheel zooms. Ctrl/⌘ Z undo, Shift Z redo; C/V copy/paste; D duplicate; A select all; Delete removes unlocked objects. Polygon: click vertices then Enter. Double-click editable objects. Escape exits presentation or cancels. Use Export → Editable backup to move lessons between devices.',submit:'Got it'});}
 onKey(e){if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;const mod=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(e.code==='Space'){e.preventDefault();this.space=true;return;}if(k==='escape'){this.draft=null;this.polygon=[];this.drag=null;this.marquee=null;Object.assign(this.board,structuredClone(this.history.current));this.selected.clear();document.body.classList.remove('presenting');this.paint();return;}if(k==='enter'&&this.tool==='polygon'){this.action(()=>this.finishPolygon());return;}
 if(mod&&['z','y','a','c','v','d','s'].includes(k)){e.preventDefault();this.action(()=>{if(k==='z')e.shiftKey?this.redo():this.undo();if(k==='y')this.redo();if(k==='a'){this.selected=new Set(this.board.items.map(i=>i.id));this.paint();}if(k==='c')this.clipboard=structuredClone(this.board.items.filter(i=>this.selected.has(i.id)));if(k==='v')this.paste();if(k==='d')this.duplicate();if(k==='s')backup(this.board);});return;}
 if(k==='delete'||k==='backspace'){e.preventDefault();this.action(()=>this.remove());return;}
 if(['arrowleft','arrowright','arrowup','arrowdown'].includes(k)){e.preventDefault();const step=e.shiftKey?10:1;for(const i of this.board.items)if(this.selected.has(i.id)&&!i.locked){i.x+=(k==='arrowright'?step:k==='arrowleft'?-step:0);i.y+=(k==='arrowdown'?step:k==='arrowup'?-step:0);}this.action(()=>this.commit());return;}
 if(!mod){const map={v:'select',h:'pan',p:'pen',e:'eraser',l:'line',r:'rectangle',o:'ellipse',t:'text'};if(map[k])this.setTool(map[k]);}}
}
