import { el,btn } from './ui.js?v=20261006-text-taps';
export const FILL_TYPES=new Set(['shape','rectangle','ellipse','triangle','polygon','note']);
export function hsvHex(h,s,v){const f=n=>{const k=(n+h/60)%6;return Math.round(255*(v-v*s*Math.max(0,Math.min(k,4-k,1)))).toString(16).padStart(2,'0');};return '#'+f(5)+f(3)+f(1);}
export function hexHsv(hex){const [r,g,b]=hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255),max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min;let h=!d?0:max===r?60*(((g-b)/d)%6):max===g?60*((b-r)/d+2):60*((r-g)/d+4);return [(h+360)%360,max?d/max:0,max];}
export function validFavorite(v){return v&&/^#[0-9a-f]{6}$/i.test(v.color)&&Number.isFinite(v.alpha)&&v.alpha>=0&&v.alpha<=1;}
const COLORS=['#000000','#303030','#585858','#808080','#aaaaaa','#d4d4d4','#eeeeee','#ffffff','none',...['#701010','#8c210c','#b16b12','#b59c0c','#377c20','#13798a','#173ea0','#6e188d','#a11066','#bb171b','#e32a0c','#ff9900','#ffcc00','#60b832','#21b1ca','#3464ea','#ae31ce','#e633a6','#da6969','#f89a77','#ffd18c','#ffe788','#b6e885','#9ddbe5','#99b2ee','#d991e4','#eda0ce','#f8dada','#ffe3d4','#fff2df','#fffbd6','#effadd','#dff6f8','#e4eafa','#f5dff9','#fbe0ee']];
export const STROKE_TYPES=new Set(['shape','path','line','arrow','curve','arc','rectangle','ellipse','triangle','polygon','note','text']);
export class FillPalette{
 constructor(editor,mode='fill'){this.e=editor;this.key=mode;this.alphaKey=mode+'Opacity';this.label=mode==='stroke'?'Stroke':'Fill';this.types=mode==='stroke'?STROKE_TYPES:FILL_TYPES;this.storageKey='teaching-board-'+mode+'-favorites';this.noneLabel=mode==='stroke'?'No stroke':'No fill';this.color='#fff1a8';this.alpha=1;this.hsv=hexHsv(this.color);this.favorites=[];try{const stored=JSON.parse(localStorage.getItem(this.storageKey)||'[]');if(Array.isArray(stored))this.favorites=stored.filter(validFavorite).slice(0,24);}catch{}this.root=el('details',null,'fill-palette');this.summary=el('summary');this.summary.setAttribute('aria-label',this.label+' palette');this.chip=el('span',null,'fill-chip');this.summary.append(el('span',this.label),this.chip,el('span','▾'));this.panel=el('div',null,'fill-panel');this.panel.setAttribute('aria-label',this.label+' colors');const tabs=el('div',null,'fill-tabs');this.defaults=btn('Default',()=>this.showTab(false));this.favs=btn('Favorites',()=>this.showTab(true));tabs.append(this.defaults,this.favs);this.grid=el('div',null,'fill-swatches');this.favoriteGrid=el('div',null,'fill-swatches');for(const color of COLORS)this.grid.append(this.swatch(color,1));
 this.canvas=el('canvas',null,'fill-spectrum');this.canvas.width=280;this.canvas.height=140;this.canvas.setAttribute('aria-label','Color spectrum; use hue, saturation and brightness controls below for keyboard input');this.canvas.style.touchAction='none';const pick=e=>{const r=this.canvas.getBoundingClientRect();this.hsv[1]=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));this.hsv[2]=1-Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));this.color=hsvHex(...this.hsv);this.refresh();};this.canvas.onpointerdown=e=>{e.preventDefault();this.canvas.setPointerCapture(e.pointerId);pick(e);};this.canvas.onpointermove=e=>{if(this.canvas.hasPointerCapture(e.pointerId))pick(e);};this.canvas.onpointerup=e=>{if(this.canvas.hasPointerCapture(e.pointerId))this.canvas.releasePointerCapture(e.pointerId);};
 this.controls=el('div',null,'fill-controls');this.hue=this.range('Hue',0,360,()=>{this.hsv[0]=+this.hue.value;this.color=hsvHex(...this.hsv);this.refresh();});this.saturation=this.range('Saturation',0,100,()=>{this.hsv[1]=+this.saturation.value/100;this.color=hsvHex(...this.hsv);this.refresh();});this.brightness=this.range('Brightness',0,100,()=>{this.hsv[2]=+this.brightness.value/100;this.color=hsvHex(...this.hsv);this.refresh();});this.opacity=this.range(this.label+' opacity',0,100,()=>{this.alpha=+this.opacity.value/100;this.refresh();});this.preview=el('span',null,'fill-preview');this.hex=el('input');this.hex.setAttribute('aria-label',this.label+' hex color');this.hex.maxLength=7;this.hex.oninput=()=>{if(/^#[0-9a-f]{6}$/i.test(this.hex.value)){this.color=this.hex.value.toLowerCase();this.hsv=hexHsv(this.color);this.refresh();}};this.message=el('p',null,'fill-message');const custom=el('div',null,'fill-custom');custom.append(this.preview,this.hex);const actions=el('div',null,'fill-actions');actions.append(btn(this.noneLabel,()=>this.apply('none',1)),btn('★ Save favorite',()=>{if(!this.favorites.some(v=>v.color===this.color&&v.alpha===this.alpha))this.favorites.push({color:this.color,alpha:this.alpha});this.favorites=this.favorites.slice(-24);this.saveFavorites();}),btn('Remove favorite',()=>{this.favorites=this.favorites.filter(v=>v.color!==this.color||v.alpha!==this.alpha);this.saveFavorites();}),btn('Apply '+mode,()=>{if(!/^#[0-9a-f]{6}$/i.test(this.hex.value)){this.message.textContent='Enter a color such as #3366cc.';return;}this.apply(this.color,this.alpha);},'primary'));this.panel.append(tabs,this.grid,this.favoriteGrid,this.canvas,this.controls,custom,this.message,actions);this.root.append(this.summary,this.panel);this.root.addEventListener('toggle',()=>{if(this.root.open)this.load();});this.root.onkeydown=e=>{e.stopPropagation();if(e.key==='Escape'){this.root.open=false;this.summary.focus();}};this.root.addEventListener('focusout',e=>{if(e.relatedTarget&&!this.root.contains(e.relatedTarget))this.root.open=false;});this.showTab(false);this.refresh();}
 range(label,min,max,action){const row=el('label',label),input=el('input');input.type='range';input.min=min;input.max=max;input.step=1;input.setAttribute('aria-label',label);input.oninput=action;row.append(input);this.controls.append(row);return input;}
 swatch(color,alpha){const b=btn('',()=>{if(color==='none'){this.apply(color,1);return;}this.color=color;this.alpha=alpha;this.hsv=hexHsv(color);this.refresh();this.apply(color,alpha);});b.className='fill-swatch';b.title=color==='none'?this.noneLabel:`${color} · ${Math.round(alpha*100)}%`;b.setAttribute('aria-label',b.title);const sample=el('span');sample.style.background=color==='none'?'transparent':color;sample.style.opacity=alpha;b.append(sample);if(color==='none')b.append(el('span','∅','no-fill-symbol'));return b;}
 showTab(favorites){this.grid.hidden=favorites;this.favoriteGrid.hidden=!favorites;this.defaults.setAttribute('aria-pressed',String(!favorites));this.favs.setAttribute('aria-pressed',String(favorites));this.renderFavorites();}
 renderFavorites(){this.favoriteGrid.replaceChildren();for(const v of this.favorites)this.favoriteGrid.append(this.swatch(v.color,v.alpha));if(!this.favorites.length)this.favoriteGrid.append(el('p','Save a custom color below.'));}
 saveFavorites(){try{localStorage.setItem(this.storageKey,JSON.stringify(this.favorites));this.message.textContent='Favorites saved on this device.';}catch{this.message.textContent='Favorites are available for this session only.';}this.renderFavorites();}
 load(){const item=this.e.board.items.find(i=>this.e.selected.has(i.id)&&this.types.has(i.type));const color=item?.[this.key]??this.e[this.key];this.color=color==='none'?'#fff1a8':color;this.alpha=item?(item[this.alphaKey]??1):this.e[this.alphaKey];this.hsv=hexHsv(this.color);this.message.textContent='';this.refresh();}
 apply(color,alpha){this.e[this.key]=color;this.e[this.alphaKey]=alpha;let changed=false;for(const item of this.e.board.items)if(this.e.selected.has(item.id)&&!item.locked&&this.types.has(item.type)){item[this.key]=color;item[this.alphaKey]=alpha;changed=true;}this.root.open=false;if(changed)this.e.commit();else this.e.paint();this.summary.focus();}
 update(){const items=this.e.board.items.filter(i=>this.e.selected.has(i.id)&&this.types.has(i.type)),color=items[0]?.[this.key]??this.e[this.key],alpha=items.length?(items[0][this.alphaKey]??1):this.e[this.alphaKey];this.chip.style.background=color==='none'?'transparent':color;this.chip.style.opacity=alpha;this.chip.textContent=color==='none'?'∅':'';this.summary.title=this.label+': '+color+' · '+Math.round(alpha*100)+'%';}
 refresh(){if(!this.hue)return;this.hue.value=this.hsv[0];this.saturation.value=this.hsv[1]*100;this.brightness.value=this.hsv[2]*100;this.opacity.value=this.alpha*100;this.opacity.setAttribute('aria-valuetext',Math.round(this.alpha*100)+'%');this.hex.value=this.color;this.preview.style.background=this.color;this.preview.style.opacity=this.alpha;const c=this.canvas.getContext('2d'),w=this.canvas.width,h=this.canvas.height;c.fillStyle=hsvHex(this.hsv[0],1,1);c.fillRect(0,0,w,h);const white=c.createLinearGradient(0,0,w,0);white.addColorStop(0,'white');white.addColorStop(1,'#ffffff00');c.fillStyle=white;c.fillRect(0,0,w,h);const black=c.createLinearGradient(0,0,0,h);black.addColorStop(0,'#00000000');black.addColorStop(1,'black');c.fillStyle=black;c.fillRect(0,0,w,h);c.beginPath();c.arc(this.hsv[1]*w,(1-this.hsv[2])*h,5,0,Math.PI*2);c.strokeStyle='#fff';c.lineWidth=2;c.stroke();}
}
