import { el, btn, field } from './ui.js?v=20261006-parameters';
import { validateParameters } from './graph-series.js?v=20261006-parameters';
import { graph } from './media.js?v=20261006-parameters';
export const GRAPH_COLORS=['#147d92','#c44861','#7c50b0','#dc8a21','#398148','#3765c2','#925830','#414d62'];
export function graphDialog(existing){const d=el('dialog',null,'form-dialog graph-dialog'),rows=el('div'),ranges=el('div',null,'graph-ranges'),preview=el('img'),error=el('p',null,'error'),actions=el('div',null,'actions');preview.className='graph-preview';preview.alt='Function, parametric and polar graph preview';let values=(existing?.series||[{source:existing?.source||'x^2',color:GRAPH_COLORS[0],visible:true}]).map(x=>({...x})),closed=false,timer,serial=0;const inputs={},parameters=structuredClone(existing?.parameters||[]),parameterPanel=el('div',null,'graph-parameters');
 for(const [key,label,value]of [['xmin','x minimum',existing?.range?.[0]??-5],['xmax','x maximum',existing?.range?.[2]??5],['ymin','y minimum',existing?.range?.[3]??-5],['ymax','y maximum',existing?.range?.[1]??5]]){const f=field(label,value,'number');f.input.step='any';inputs[key]=f.input;f.input.oninput=schedule;ranges.append(f.wrap);}
 const range=()=>[+inputs.xmin.value,+inputs.ymax.value,+inputs.xmax.value,+inputs.ymin.value];
 function drawRows(){rows.replaceChildren();values.forEach((v,k)=>{const row=el('div',null,'graph-row'),show=el('input'),color=el('input'),source=el('input');show.type='checkbox';show.checked=v.visible!==false;show.setAttribute('aria-label',`Show function ${k+1}`);color.type='color';color.value=v.color;color.setAttribute('aria-label',`Function ${k+1} color`);source.value=v.source;source.placeholder='sin(x)';source.setAttribute('aria-label',`Function ${k+1}`);show.onchange=()=>{v.visible=show.checked;schedule();};color.oninput=()=>{v.color=color.value;schedule();};source.oninput=()=>{v.source=source.value;schedule();};const kind=el('select');kind.setAttribute('aria-label',`Curve ${k+1} type`);for(const [key,label]of [['function','y = f(x)'],['parametric','Parametric'],['polar','Polar: r(t)']]){const o=el('option',label);o.value=key;kind.append(o);}kind.value=v.kind||'function';kind.onchange=()=>{v.kind=kind.value;if(v.kind==='parametric'){v.xSource=v.xSource||'cos(t)';v.source='sin(t)';v.tmin=v.tmin??0;v.tmax=v.tmax??2*Math.PI;}else if(v.kind==='polar'){v.source='2*(1+cos(t))';v.tmin=0;v.tmax=2*Math.PI;}else v.source='x^2';drawRows();schedule();};const remove=btn('×',()=>{if(values.length===1)return;values.splice(k,1);drawRows();schedule();});remove.setAttribute('aria-label',`Remove function ${k+1}`);row.append(show,color,kind,remove);const expressions=el('div',null,'graph-expressions');if(['parametric','polar'].includes(v.kind)){const polar=v.kind==='polar',x=field('x(t)',v.xSource),lo=field(polar?'Angle minimum (radians)':'t minimum',v.tmin,'number'),hi=field(polar?'Angle maximum (radians)':'t maximum',v.tmax,'number');x.input.setAttribute('aria-label',`Curve ${k+1} x(t)`);x.input.oninput=()=>{v.xSource=x.input.value;schedule();};for(const [f,key]of [[lo,'tmin'],[hi,'tmax']]){f.input.step='any';f.input.setAttribute('aria-label',`Curve ${k+1} ${key==='tmin'?'t minimum':'t maximum'}`);f.input.oninput=()=>{v[key]=f.input.value===''?NaN:+f.input.value;schedule();};}const y=el('label',polar?'r(t)':'y(t)');source.setAttribute('aria-label',`Curve ${k+1} ${polar?'r(t)':'y(t)'}`);source.placeholder=polar?'2*(1+cos(t))':'sin(t)';y.append(source);if(!polar)expressions.append(x.wrap);expressions.append(y,lo.wrap,hi.wrap);}else{const label=el('label','y =');label.append(source);expressions.append(label);}const block=el('div',null,'graph-curve-block');block.append(row,expressions);rows.append(block);});}
 function drawParameters(){parameterPanel.replaceChildren(el('h3','Shared parameters'),el('p','Use a, b or c in any curve. Adjust the slider to preview, then Insert graph to save the current value.','muted'));for(const p of parameters){const block=el('div',null,'graph-curve-block'),line=el('div',null,'graph-ranges'),slider=el('input');slider.type='range';slider.min=p.min;slider.max=p.max;slider.step='any';slider.value=p.value;slider.setAttribute('aria-label',`Parameter ${p.name} slider`);let valueInput;for(const [key,label]of [['value',p.name+' value'],['min',p.name+' minimum'],['max',p.name+' maximum']]){const f=field(label,p[key],'number');f.input.step='any';if(key==='value')valueInput=f.input;f.input.oninput=()=>{p[key]=f.input.value===''?NaN:+f.input.value;try{validateParameters(parameters);slider.min=p.min;slider.max=p.max;slider.value=p.value;}catch{}schedule();};line.append(f.wrap);}slider.oninput=()=>{p.value=+slider.value;valueInput.value=p.value;schedule();};block.append(line,slider,btn('Remove '+p.name,()=>{parameters.splice(parameters.indexOf(p),1);drawParameters();schedule();}));parameterPanel.append(block);}parameterPanel.append(btn('+ Add parameter',()=>{const name=['a','b','c'].find(n=>!parameters.some(p=>p.name===n));if(!name){error.textContent='Use up to three parameters.';return;}parameters.push({name,value:1,min:-10,max:10});drawParameters();schedule();}));}
 function schedule(){clearTimeout(timer);timer=setTimeout(update,300);}
 async function update(){const id=++serial;try{const result=await graph(values,range(),parameters);if(closed||id!==serial)return;preview.src=result.src;error.textContent='';}catch(e){if(!closed&&id===serial){error.textContent=e.message;preview.removeAttribute('src');}}}
 d.append(el('h2','Function, parametric and polar graphs'),el('p','Up to 8 curves share the axes. Choose y = f(x), Parametric: x(t), y(t), or Polar: r(t). Polar t is the angle measured counterclockwise from the positive x-axis; negative radii are supported. Angles are radians; use sin, cos, sqrt, abs, pi and explicit multiplication (2*t). Changing curve type starts a new example.','muted'),rows,btn('+ Add curve',()=>{if(values.length>=8){error.textContent='Use up to 8 curves.';return;}values.push({source:'sin(x)',color:GRAPH_COLORS[values.length],visible:true});drawRows();schedule();}),parameterPanel,ranges,preview,error,actions);document.body.append(d);drawRows();drawParameters();
 const promise=new Promise(resolve=>{let result=null;actions.append(btn('Cancel',()=>d.close()),btn('Insert graph',async()=>{try{result=await graph(values,range(),parameters);if(!closed)d.close();}catch(e){error.textContent=e.message;}},'primary'));d.onclose=()=>{closed=true;serial++;clearTimeout(timer);d.remove();resolve(result);};});d.showModal();update();return promise;}
