import { el, btn, field } from './ui.js?v=20261006-parametric';
import { graph } from './media.js?v=20261006-parametric';
export const GRAPH_COLORS=['#147d92','#c44861','#7c50b0','#dc8a21','#398148','#3765c2','#925830','#414d62'];
export function graphDialog(existing){const d=el('dialog',null,'form-dialog graph-dialog'),rows=el('div'),ranges=el('div',null,'graph-ranges'),preview=el('img'),error=el('p',null,'error'),actions=el('div',null,'actions');preview.className='graph-preview';preview.alt='Function and parametric graph preview';let values=(existing?.series||[{source:existing?.source||'x^2',color:GRAPH_COLORS[0],visible:true}]).map(x=>({...x})),closed=false,timer,serial=0;const inputs={};
 for(const [key,label,value]of [['xmin','x minimum',existing?.range?.[0]??-5],['xmax','x maximum',existing?.range?.[2]??5],['ymin','y minimum',existing?.range?.[3]??-5],['ymax','y maximum',existing?.range?.[1]??5]]){const f=field(label,value,'number');f.input.step='any';inputs[key]=f.input;f.input.oninput=schedule;ranges.append(f.wrap);}
 const range=()=>[+inputs.xmin.value,+inputs.ymax.value,+inputs.xmax.value,+inputs.ymin.value];
 function drawRows(){rows.replaceChildren();values.forEach((v,k)=>{const row=el('div',null,'graph-row'),show=el('input'),color=el('input'),source=el('input');show.type='checkbox';show.checked=v.visible!==false;show.setAttribute('aria-label',`Show function ${k+1}`);color.type='color';color.value=v.color;color.setAttribute('aria-label',`Function ${k+1} color`);source.value=v.source;source.placeholder='sin(x)';source.setAttribute('aria-label',`Function ${k+1}`);show.onchange=()=>{v.visible=show.checked;schedule();};color.oninput=()=>{v.color=color.value;schedule();};source.oninput=()=>{v.source=source.value;schedule();};const kind=el('select');kind.setAttribute('aria-label',`Curve ${k+1} type`);for(const [key,label]of [['function','y = f(x)'],['parametric','Parametric']]){const o=el('option',label);o.value=key;kind.append(o);}kind.value=v.kind||'function';kind.onchange=()=>{v.kind=kind.value;if(v.kind==='parametric'){v.xSource=v.xSource||'cos(t)';v.source='sin(t)';v.tmin=v.tmin??0;v.tmax=v.tmax??2*Math.PI;}else v.source='x^2';drawRows();schedule();};const remove=btn('×',()=>{if(values.length===1)return;values.splice(k,1);drawRows();schedule();});remove.setAttribute('aria-label',`Remove function ${k+1}`);row.append(show,color,kind,remove);const expressions=el('div',null,'graph-expressions');if(v.kind==='parametric'){const x=field('x(t)',v.xSource),lo=field('t minimum',v.tmin,'number'),hi=field('t maximum',v.tmax,'number');x.input.setAttribute('aria-label',`Curve ${k+1} x(t)`);x.input.oninput=()=>{v.xSource=x.input.value;schedule();};for(const [f,key]of [[lo,'tmin'],[hi,'tmax']]){f.input.step='any';f.input.setAttribute('aria-label',`Curve ${k+1} ${key==='tmin'?'t minimum':'t maximum'}`);f.input.oninput=()=>{v[key]=f.input.value===''?NaN:+f.input.value;schedule();};}const y=el('label','y(t)');source.setAttribute('aria-label',`Curve ${k+1} y(t)`);source.placeholder='sin(t)';y.append(source);expressions.append(x.wrap,y,lo.wrap,hi.wrap);}else{const label=el('label','y =');label.append(source);expressions.append(label);}const block=el('div',null,'graph-curve-block');block.append(row,expressions);rows.append(block);});}
 function schedule(){clearTimeout(timer);timer=setTimeout(update,300);}
 async function update(){const id=++serial;try{const result=await graph(values,range());if(closed||id!==serial)return;preview.src=result.src;error.textContent='';}catch(e){if(!closed&&id===serial){error.textContent=e.message;preview.removeAttribute('src');}}}
 d.append(el('h2','Function and parametric graphs'),el('p','Up to 8 curves share the axes. Choose y = f(x) or Parametric: x(t), y(t). Angles are radians; use sin, cos, sqrt, abs, pi and explicit multiplication (2*t). Changing curve type starts a new example.','muted'),rows,btn('+ Add curve',()=>{if(values.length>=8){error.textContent='Use up to 8 curves.';return;}values.push({source:'sin(x)',color:GRAPH_COLORS[values.length],visible:true});drawRows();schedule();}),ranges,preview,error,actions);document.body.append(d);drawRows();
 const promise=new Promise(resolve=>{let result=null;actions.append(btn('Cancel',()=>d.close()),btn('Insert graph',async()=>{try{result=await graph(values,range());if(!closed)d.close();}catch(e){error.textContent=e.message;}},'primary'));d.onclose=()=>{closed=true;serial++;clearTimeout(timer);d.remove();resolve(result);};});d.showModal();update();return promise;}
