import { el, btn, field } from './ui.js?v=20260928-cropfix';
import { graph } from './media.js?v=20260928-cropfix';
export const GRAPH_COLORS=['#147d92','#c44861','#7c50b0','#dc8a21','#398148','#3765c2','#925830','#414d62'];
export function graphDialog(existing){const d=el('dialog',null,'form-dialog graph-dialog'),rows=el('div'),ranges=el('div',null,'graph-ranges'),preview=el('img'),error=el('p',null,'error'),actions=el('div',null,'actions');preview.className='graph-preview';preview.alt='Multi-function graph preview';let values=(existing?.series||[{source:existing?.source||'x^2',color:GRAPH_COLORS[0],visible:true}]).map(x=>({...x})),closed=false,timer,serial=0;const inputs={};
 for(const [key,label,value]of [['xmin','x minimum',existing?.range?.[0]??-5],['xmax','x maximum',existing?.range?.[2]??5],['ymin','y minimum',existing?.range?.[3]??-5],['ymax','y maximum',existing?.range?.[1]??5]]){const f=field(label,value,'number');f.input.step='any';inputs[key]=f.input;f.input.oninput=schedule;ranges.append(f.wrap);}
 const range=()=>[+inputs.xmin.value,+inputs.ymax.value,+inputs.xmax.value,+inputs.ymin.value];
 function drawRows(){rows.replaceChildren();values.forEach((v,k)=>{const row=el('div',null,'graph-row'),show=el('input'),color=el('input'),source=el('input');show.type='checkbox';show.checked=v.visible!==false;show.setAttribute('aria-label',`Show function ${k+1}`);color.type='color';color.value=v.color;color.setAttribute('aria-label',`Function ${k+1} color`);source.value=v.source;source.placeholder='sin(x)';source.setAttribute('aria-label',`Function ${k+1}`);show.onchange=()=>{v.visible=show.checked;schedule();};color.oninput=()=>{v.color=color.value;schedule();};source.oninput=()=>{v.source=source.value;schedule();};const remove=btn('×',()=>{if(values.length===1)return;values.splice(k,1);drawRows();schedule();});remove.setAttribute('aria-label',`Remove function ${k+1}`);row.append(show,color,el('span','y ='),source,remove);rows.append(row);});}
 function schedule(){clearTimeout(timer);timer=setTimeout(update,300);}
 async function update(){const id=++serial;try{const result=await graph(values,range());if(closed||id!==serial)return;preview.src=result.src;error.textContent='';}catch(e){if(!closed&&id===serial){error.textContent=e.message;preview.removeAttribute('src');}}}
 d.append(el('h2','Multi-function graph'),el('p','Up to 8 functions share the same axes. Use x, sin(x), cos(x), sqrt(x), abs(x), pi; write multiplication as 2*x.','muted'),rows,btn('+ Add function',()=>{if(values.length>=8){error.textContent='Use up to 8 functions.';return;}values.push({source:'sin(x)',color:GRAPH_COLORS[values.length],visible:true});drawRows();schedule();}),ranges,preview,error,actions);document.body.append(d);drawRows();
 const promise=new Promise(resolve=>{let result=null;actions.append(btn('Cancel',()=>d.close()),btn('Insert graph',async()=>{try{result=await graph(values,range());if(!closed)d.close();}catch(e){error.textContent=e.message;}},'primary'));d.onclose=()=>{closed=true;serial++;clearTimeout(timer);d.remove();resolve(result);};});d.showModal();update();return promise;}
