import { compileExpression } from './expression.js';
const loaders=new Map();
function script(url){if(!loaders.has(url))loaders.set(url,new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=()=>{s.remove();loaders.delete(url);reject(new Error('Could not load the teaching library. Check your internet connection and retry.'));};document.head.append(s);}));return loaders.get(url);}
export function dataURL(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob);});}
export function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error('Image could not be decoded.'));image.src=src;});}
export async function rasterSVG(svg,width,height){const source=new XMLSerializer().serializeToString(svg),url=URL.createObjectURL(new Blob([source],{type:'image/svg+xml'}));try{const image=await loadImage(url),canvas=document.createElement('canvas');canvas.width=Math.ceil(width*2);canvas.height=Math.ceil(height*2);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png');}finally{URL.revokeObjectURL(url);}}
export async function equation(source){if(!source.trim()||source.length>2000)throw new Error('Enter a LaTeX expression (up to 2,000 characters).');if(!window.MathJax?.tex2svgPromise){window.MathJax={loader:{load:['ui/safe']},svg:{fontCache:'none'},options:{enableMenu:false}};await script('https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-svg.js');await window.MathJax.startup.promise;}
 const node=await MathJax.tex2svgPromise(source,{display:true});if(node.querySelector('[data-mml-node="merror"]'))throw new Error('Check the LaTeX expression.');const svg=node.querySelector('svg');const vb=svg.getAttribute('viewBox').split(/\s+/).map(Number);const h=Math.min(350,Math.max(45,vb[3]/40)),w=Math.min(1800,Math.max(60,h*vb[2]/vb[3]));svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width',w);svg.setAttribute('height',h);svg.style.color='#172c45';return {src:await rasterSVG(svg,w,h),w,h,source};}
export async function graph(source,range){const fn=compileExpression(source);if(!range.every(Number.isFinite)||range[0]>=range[2]||range[3]>=range[1]||range.some(x=>Math.abs(x)>100000))throw new Error('Use valid graph bounds: minimum smaller than maximum.');await script('https://cdn.jsdelivr.net/npm/jsxgraph@1.11.1/distrib/jsxgraphcore.js');
 const host=document.createElement('div');host.id='graph-'+crypto.randomUUID();host.style.cssText='position:fixed;left:-10000px;top:0;width:640px;height:440px;direction:ltr;background:white';document.body.append(host);let board;try{board=JXG.JSXGraph.initBoard(host.id,{boundingbox:range,axis:true,grid:true,showCopyright:false,showNavigation:false,keepaspectratio:false,defaultAxes:{x:{ticks:{label:{display:'internal'}}},y:{ticks:{label:{display:'internal'}}}});board.create('functiongraph',[x=>{const y=fn(x);return Number.isFinite(y)?y:NaN;}],{strokeColor:'#147d92',strokeWidth:3});board.fullUpdate();const svg=host.querySelector('svg').cloneNode(true);svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','640');svg.setAttribute('height','440');return {src:await rasterSVG(svg,640,440),w:640,h:440,source,range};}finally{if(board)JXG.JSXGraph.freeBoard(board);host.remove();}}
export async function importImage(file){if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>15_000_000)throw new Error('Choose PNG, JPEG, WebP or GIF under 15 MB.');const image=await loadImage(await dataURL(file));const scale=Math.min(1,2200/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return {src:canvas.toDataURL('image/png'),w:Math.min(800,canvas.width),h:Math.min(800,canvas.width)*canvas.height/canvas.width};}
export async function importPDF(file,progress){if(file.size>30_000_000)throw new Error('Choose a PDF under 30 MB.');const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs';const loading=pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false});let pdf;try{pdf=await loading.promise;if(pdf.numPages>30)throw new Error('Import up to 30 PDF pages at a time.');const pages=[];let bytes=0;for(let n=1;n<=pdf.numPages;n++){progress(`Importing page ${n} of ${pdf.numPages}…`);const page=await pdf.getPage(n),base=page.getViewport({scale:1}),viewport=page.getViewport({scale:Math.min(2,1600/base.width)}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const src=canvas.toDataURL('image/jpeg',.86);bytes+=src.length;if(bytes>20_000_000)throw new Error('PDF images are too large. Import fewer pages.');pages.push({src,w:800,h:800*viewport.height/viewport.width});page.cleanup();}return pages;}finally{await loading.destroy();}}
