import { el, btn, confirmDialog } from './ui.js?v=20260930-stroke';
import { svgEl, drawItem, background } from './scene.js?v=20260930-stroke';
export const A4={w:794,h:1123,gap:32};
export const pageRect=index=>({x:0,y:index*(A4.h+A4.gap),w:A4.w,h:A4.h});
export function deletePage(board,index){const top=pageRect(index).y,bottom=top+A4.h+A4.gap;board.items=board.items.filter(i=>{const center=i.y+(i.h||1)/2;return !(center>=top&&center<bottom&&i.x+(i.w||1)/2>=0&&i.x+(i.w||1)/2<=A4.w);}).map(i=>i.y>=bottom?{...i,y:i.y-A4.h-A4.gap}:i);board.pageCount--;}
export function pageSVG(board,index){const r=pageRect(index),s=svgEl('svg',{xmlns:'http://www.w3.org/2000/svg',width:r.w,height:r.h,viewBox:`0 0 ${r.w} ${r.h}`});background(s,board.background,{x:0,y:-r.y,zoom:1},'page-paper-'+index);const g=svgEl('g',{transform:`translate(0 ${-r.y})`});board.items.forEach(i=>g.append(drawItem(i)));s.append(g);return s;}
export class Pages{
 constructor(editor){this.e=editor;this.index=0;}
 controls(){const e=this.e,bar=el('div',null,'page-controls'),mode=el('select');mode.setAttribute('aria-label','Canvas layout');for(const [value,label]of [['infinite','Infinite canvas'],['a4','A4 pages']]){const o=el('option',label);o.value=value;mode.append(o);}this.mode=mode;mode.onchange=()=>{e.board.layout=mode.value;e.board.pageCount=e.board.pageCount||1;e.commit();if(mode.value==='a4')this.go(0);};this.label=el('span');this.previous=btn('‹',()=>this.go(this.index-1));this.previous.title='Previous page';this.next=btn('›',()=>this.go(this.index+1));this.next.title='Next page';this.add=btn('+ Page',()=>{if(e.board.pageCount>=100)return;e.board.pageCount++;e.commit();this.go(e.board.pageCount-1);});this.remove=btn('Delete page',async()=>{if(e.board.pageCount<=1)return;if(await confirmDialog('Delete this page?', 'Objects centered on this page will be deleted, including locked objects. Later pages move up. Undo restores the page.')){deletePage(e.board,this.index);e.selected.clear();e.commit();this.go(this.index);}});bar.append(mode,this.previous,this.label,this.next,this.add,this.remove);return bar;}
 update(){const b=this.e.board,on=b.layout==='a4';this.index=Math.max(0,Math.min(this.index,(b.pageCount||1)-1));this.mode.value=b.layout||'infinite';for(const n of [this.previous,this.label,this.next,this.add,this.remove])n.hidden=!on;this.label.textContent=`${this.index+1} / ${b.pageCount||1}`;this.previous.disabled=this.index===0;this.next.disabled=this.index>=(b.pageCount||1)-1;this.remove.disabled=(b.pageCount||1)<=1;this.add.disabled=(b.pageCount||1)>=100;}
 go(index){const e=this.e;this.index=Math.max(0,Math.min(index,(e.board.pageCount||1)-1));const r=pageRect(this.index),zoom=Math.max(.1,Math.min(2,(e.area.clientWidth-60)/r.w,(e.area.clientHeight-70)/r.h));e.board.viewport={zoom,x:(e.area.clientWidth-r.w*zoom)/2,y:35-r.y*zoom};e.paint();e.save();}
 paint(scene){const b=this.e.board;if(b.layout!=='a4')return;for(let n=0;n<(b.pageCount||1);n++){const r=pageRect(n);scene.append(svgEl('rect',{...r,width:r.w,height:r.h,fill:b.background==='dark'?'#1d293b':'#fff',stroke:'#8b9bab','stroke-width':2}));const s=pageSVG({...b,items:[]},n);s.setAttribute('x',r.x);s.setAttribute('y',r.y);scene.append(s);const label=svgEl('text',{x:8,y:r.y-8,fill:'#63758a','font-size':14});label.textContent=`A4 · ${n+1}`;scene.append(label);}}
}
